package jp.osdn.gokigen.inventorymanager.storage

enum class SortOrderDirection {
    CREATE_NEWEST, CREATE_OLDEST, UPDATE_NEWEST, UPDATE_OLDEST, TITLE_ASCENDING, TITLE_DESCENDING, AUTHOR_ASCENDING, AUTHOR_DESCENDING, PUBLISHER_ASCENDING, PUBLISHER_DESCENDING,
}
